### ISSUE TITLE
Confidence level

### ISSUE THREAD

**Issue by AlbinOS** [matttproud/golang_protobuf_extensions#12]
Dear Matt,

Really enjoying the great work on this lib. 

Do you think it's safe to use this in production and if not, what do you think needs work ? I'm happy to help you on that. 

We'll need to decode incoming protobuf from an external Java application advising the use of their protobuf like this :

```java
// parse all frames
CoordinatesFrame frame = CoordinatesFrame.parseDelimitedFrom(in);
while (frame != null) {
	System.out.println("FRAME: " + frame.getTimestamp() + " " + frame.getCoordinatesCount());
	frame = CoordinatesFrame.parseDelimitedFrom(in);
}
``` 

So far using you extensions with the generated .pb.go is working. I'm using it like this :

```go
inBuffer := bytes.NewReader(in)

i := 0
n := 1
for n > 0 {
	coordinates := &CoordinatesFrame{}
	n, err = pbutil.ReadDelimited(inBuffer, coordinates4)
	if err != nil {
		log.Errorf("Kaput unmarshaling proto: %s", err)
	}

	// Use coordinates here

	i++
}
```

Regards from Belgium,
Albin.

**Comment by matttproud** [comment]
@AlbinOS, the library is production ready and used in a number of critical pieces of software.  One thing to be aware of: the record-length delimited Protocol Buffer does not standardize across the official implementation whether the delimiter is a 32- or 64-bit varint.  I don't anticipate you'll be using Protocol Buffers to serialize `2^32` byte messages, so you'll probably be fine.  Does that help?

**Comment by AlbinOS** [comment]
@matttproud, it's wonderful, thanks ! :-)
