### ISSUE TITLE
pbutil: dependencies/tests fail with github.com/golang/protobuf v1.1.0

### ISSUE THREAD

**Issue by mpx** [matttproud/golang_protobuf_extensions#13]
github.com/golang/protobuf v1.1.0 (and later) have removed the testdata directory so it can no longer be imported. This breaks tests:

```
$ go test
# github.com/matttproud/golang_protobuf_extensions/pbutil
all_test.go:27:2: cannot find package "github.com/golang/protobuf/proto/testdata" in any of:
	/home/mark/go1.10.2/src/github.com/golang/protobuf/proto/testdata (from $GOROOT)
	/home/mark/src/github.com/golang/protobuf/proto/testdata (from $GOPATH)
FAIL	github.com/matttproud/golang_protobuf_extensions/pbutil [setup failed]
```

I noticed this when attempting to use `vgo vendor` with a module that depends on `github.com/prometheus/client_golang/prometheus`. vgo is unable to enumerate dependencies since pbutil's dependencies are broken.

**Comment by mpx** [comment]
Ahh, I just noticed I was using v1.0.0 which doesn't include the fix in c12348c.

Can you please tag a new release?

**Comment by matttproud** [comment]
Thanks for noticing.  I had expected vgo would not be happy about something.

https://github.com/matttproud/golang_protobuf_extensions/releases/tag/v1.0.1

**Comment by sneko** [comment]
Hi! @mpx how did you succeed in solving this issue? On my side I'm trying to import the Prometheus Metrics library but I got same kind of error.
```
        import "github.com/go-kit/kit/metrics/prometheus" ->
        import "github.com/prometheus/client_golang/prometheus" ->
        import "github.com/prometheus/common/expfmt" ->
        import "github.com/matttproud/golang_protobuf_extensions/pbutil" ->
        import "github.com/golang/protobuf/proto/testdata" 
```

It tries to get "github.com\golang\protobuf@v1.1.0\proto\testdata" but it fails... Any idea how to simply fix that please?

**Comment by Albadrany99** [comment]
I won't staudi Lange program soft Woord ? 
I don't now stadium what whrait in from project search open ....!
