### ISSUE TITLE
Tag a v1.0.2 release

### ISSUE THREAD

**Issue by thaJeztah** [matttproud/golang_protobuf_extensions#17]
I noticed that the last release is missing https://github.com/matttproud/golang_protobuf_extensions/pull/15, and does not yet have a go.mod;

https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.1...c182affec369e30f25d3eb8cd8a478dee585ae7d

Some projects started to pin the dependency to that commit, instead of the last release; would it be possible to tag a v1.0.2 from master? @matttproud

**Comment by matttproud** [comment]
Sure.  I will be doing a revamp of the internals of this package for Go 1.19 as well, but the tag at `v1.0.2` is done now.

**Comment by thaJeztah** [comment]
Thanks!
